version: '2'

services:
  db1:
    image: postgres:9.6.1
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRESS_PASSWORD: db1pwd
      POSTGRESS_USER: db1usr
      POSTGRES_DB: db1db

  db2:
    image: mongo:3.0.14
    volumes:
      - db_data:/var/lib/mongo/data
    restart: always
    ports:
      - 27017
    command: "--smallfiles --logpath=/dev/null"
    environment:
      MONGODB_PASS: db2pwd
      MONGODB_USER: db2usr
      MONGODB_DATABASE: db2db

  app1:
    build: .
    ports:
      - "1337:1337"

  web:
    depends_on:
      - db1
      - db2
      - app1
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  db_data:
